# -----------------------------------Set Up------------------------------------
variables:
    PY_VERSION: 2
    TMPDIR: ./tmp
    DATADIR: /home/mebner/data/ci/CIS30FU
    VENV: pysitk-test-py${PY_VERSION}
    ITK_DIR: /mnt/shared/mebner/environment/ITK/ITK_NiftyMIC-python${PY_VERSION}-build
    FSL_DIR: /mnt/shared/mebner/environment/FSL/fsl
    NIFTYREG_INSTALL: /mnt/shared/mebner/environment/NiftyReg/NiftyReg-master-install
    CONVERT3D_INSTALL: /mnt/shared/mebner/environment/Convert3D/c3d-git-install

before_script:
    # add NiftyReg to PATH
    - export PATH="${NIFTYREG_INSTALL}/bin:$PATH"

    # add FSL
    - PATH=${FSL_DIR}/bin:${PATH}
    - export PATH="${FSL_INSTALL}/bin:$PATH"
    - export FSLOUTPUTTYPE=NIFTI_GZ

    # add Convert3D to PATH
    - export PATH="${CONVERT3D_INSTALL}/bin:$PATH"

    # save current folder path
    - cwd_dir=$(pwd)

    # create virtual environment
    - rm -rf ${VENV}
    - mypython=$(which python${PY_VERSION})
    - virtualenv -p $mypython ${VENV}
    - cd ${VENV}
    - venv_dir=$(pwd)
    - source bin/activate
    
    # print Python version to CI output
    - which python
    - python --version

    # copy ITK_NiftyMIC-build WrapITK to site-packages of python venv
    - py_sitepkg=${venv_dir}/lib/python*/site-packages
    - cp -v ${ITK_DIR}/Wrapping/Generators/Python/WrapITK.pth ${py_sitepkg}

    # add CI_JOB_TOKEN for cloning dependent repositories in requirements.txt
    # (https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories)
    - cd $cwd_dir
    - sed -i -- "s/cmiclab/gitlab-ci-token:${CI_JOB_TOKEN}@cmiclab/g" requirements.txt

    # set environment variables for installation
    - export NIFTYMIC_ITK_DIR=$ITK_DIR

    # install requirements
    - pip install -r requirements.txt

    # run installation
    - pip install -e .

after_script:
    # delete tmp-directory
    - rm -rfv ${TMPDIR}

# ----------------------------------Test Jobs----------------------------------
builddocs:
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

installation:
  script:
    - python -m nose tests/installation_test.py
  tags:
    - gift-adelie

correct_motion:
  script:
    - >
      python vrpf_correct_motion.py 
      --stack ${DATADIR}/SemiAutomaticExtraction_A5208316-B0702861-5yr.nii.gz 
      --reference ${DATADIR}/Reference_A5208316-B0702861-20yr-0-PD.nii.gz 
      --dir-output ${TMPDIR} 
      --dir-output-verbose ${TMPDIR} 
      --iter-max 10 
      --factor-downsampling 20 
      --factor-inplane-spacing 1 
      --verbose 0
  tags:
    - gift-adelie    

correct_motion_rigid_only:
  script:
    - >
      python vrpf_correct_motion.py 
      --stack ${DATADIR}/SemiAutomaticExtraction_A5208316-B0702861-5yr.nii.gz 
      --reference ${DATADIR}/Reference_A5208316-B0702861-20yr-0-PD.nii.gz 
      --dir-output ${TMPDIR} 
      --dir-output-verbose ${TMPDIR} 
      --iter-max 10
      --rigid-only 1
      --factor-downsampling 23.5 
      --factor-inplane-spacing 1 
      --verbose 0
  tags:
    - gift-adelie 

reconstruct_volume:
  script:
    - >
      python vrpf_reconstruct_volume.py 
      --stack ${DATADIR}/SemiAutomaticExtraction_A5208316-B0702861-5yr.nii.gz  
      --reference ${DATADIR}/Reference_A5208316-B0702861-20yr-0-PD.nii.gz 
      --dir-input ${DATADIR}/A5208316-B0702861-5yr_motion_correction/Affine 
      --dir-output ${TMPDIR} 
      --regularization TV 
      --alpha 5 
      --rho 0.5 
      --sigma2 0.25 
      --resolution-processing 1 
      --resolution-reconstruction 2 
      --iterations 5 
      --iter-max 5 
      --verbose 0
  tags:
    - gift-adelie

reconstruct_volume_no_ic:
  script:
    - >
      python vrpf_reconstruct_volume.py 
      --stack ${DATADIR}/SemiAutomaticExtraction_A5208316-B0702861-5yr.nii.gz  
      --reference ${DATADIR}/Reference_A5208316-B0702861-20yr-0-PD.nii.gz 
      --dir-input ${DATADIR}/A5208316-B0702861-5yr_motion_correction/Affine 
      --dir-output ${TMPDIR} 
      --regularization TK1 
      --alpha 0.05 
      --resolution-processing 1 
      --resolution-reconstruction 2 
      --iterations 5 
      --iter-max 5 
      --verbose 0
      --sigma2 -1 
      --intensity-correction 0
  tags:
    - gift-adelie
