# -----------------------------------Set Up------------------------------------
variables:
    PY_VERSION: 2
    TMPDIR: ./tmp
    VENV: pysitk-test-py${PY_VERSION}
    ITK_DIR: /mnt/shared/mebner/environment/ITK/ITK_NiftyMIC-python${PY_VERSION}-build/
    ITK_WRAPITK: ${ITK_DIR}/Wrapping/Generators/Python/WrapITK.pth
    NIFTYREG_INSTALL: /mnt/shared/mebner/environment/NiftyReg/NiftyReg-master-install
    FSL_INSTALL: /mnt/shared/mebner/environment/FSL/fsl/
    CONVERT3D_INSTALL: /mnt/shared/mebner/environment/Convert3D/c3d-git-install

before_script:
    # add NiftyReg to path
    - export PATH="${NIFTYREG_INSTALL}/bin:$PATH"

    # add FSL
    - export PATH="${FSL_INSTALL}/bin:$PATH"

    # add Convert3D to path
    - export PATH="${CONVERT3D_INSTALL}/bin:$PATH"

    # save PySiTK folder path just in case
    - export pysitk_dir=$(pwd)

    # create a virtual env to dev-test
    - rm -rf ${VENV}
    - mypython=$(which python${PY_VERSION})
    - virtualenv -p $mypython ${VENV}
    - cd ${VENV}
    - venv_dir=$(pwd)
    - source bin/activate
    
    # print Python version to CI output
    - which python
    - python --version

    # copy ITK_NiftyMIC-build WrapITK to site-packages of python venv
    - py_sitepkg=${venv_dir}/lib/python*/site-packages
    - cp -v ${ITK_DIR}/Wrapping/Generators/Python/WrapITK.pth ${py_sitepkg}

    # add CI_JOB_TOKEN for cloning dependent repositories in requirements.txt
    # (https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories)
    - cd $pysitk_dir
    - sed -i -- "s/cmiclab/gitlab-ci-token:${CI_JOB_TOKEN}@cmiclab/g" requirements.txt

    # install requirements
    - pip install -r requirements.txt

    # set environment variables for installation
    - export NIFTYMIC_ITK_DIR=$ITK_DIR

    # run installation
    - pip install -e .

after_script:
    # delete tmp-directory
    - rm -rfv ${TMPDIR}

# ----------------------------------Test Jobs----------------------------------

builddocs:
  only:
    - master
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

correct_motion:
  only:
    - master
  script:
    - python vrpf_correct_motion.py --stack ${data_dir}/SemiAutomaticExtraction_A5208316-B0702861-5yr.nii.gz  --reference ${data_dir}/Reference_A5208316-B0702861-20yr-0-PD.nii.gz --dir-output ${output_dir} --dir-output-verbose ${output_dir} --itermax 10 --factor-downsampling 20 --factor-inplane-spacing 1 --verbose 0
    tags:
        - gift-adelie    

reconstruct_volume:
  only:
    - master
  script:
    - python vrpf_reconstruct_volume.py --stack ${data_dir}/SemiAutomaticExtraction_A5208316-B0702861-5yr.nii.gz  --reference ${data_dir}/Reference_A5208316-B0702861-20yr-0-PD.nii.gz --dir-input ${output_dir}/Affine --dir-output ${output_dir} --regularization TV --alpha 5 --rho 0.5 --sigma 0.25 --resolution-processing 1 --resolution-reconstruction 2 --iterations 5 --iter-max 5 --verbose 0
  tags:
    - gift-adelie    